## Group 6
#### Obianujunwa Nwaiwu
#### Ogechi Ideozu
#### Kosemani Adegbenro
#### Oluwanifesimi Okesola
#### Juliet Uti
#### Mirriam Awio team leader 
#### Ogechukwu Nwankwo
#### Oluwabori Soyele
#### Oluwabunmi Meshach
#### Nkechi Ayama

 # 20 Numpy and Pandas Functions, their uses with examples

## 20 Numpy Functions

### Arithmetic Functions

#### 1. #sin function: np.sin() Sin function returns the sine of input in radians. The input can be a number or an array or a matrix.

In [3]:
import numpy as np

In [4]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [5]:
arr = np.array([90])
print(np.sin(arr))

[0.89399666]


#### 2. tanfunction: np.tan() tan function returns the tangent of input in radians. The input can be a number or an array or a matrix,

In [6]:

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.tan(arr))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


#### 3. cos functions: np.cos() cos function returns the cosine of input in radians. The input can be a number or an array or a matrix,

In [7]:

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.cos(arr))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


#### 4. expfunction: np.exp()The exponential of a matrix is always an invertible matrix. An invertible matrix is a square matrix  whose inverse matrix can be calculated, that is, the product of an invertible matrix and its inverse equals to the identity matrix.The inverse matrix of eX is given by e−X.

In [8]:
 arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.exp(arr))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


#### 5. squareroot: sqrt() function is a predefined function that is defined in the math module.  np.sqrt() function returns the square root of the number passed as an argument.

In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.sqrt(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


### Shape Manipulation function -  Changing the shape of an array.
##### An array has a shape given by the number of elements along each axis:


#### 6. To get shape of the array


In [12]:
import numpy as np
a = np.array([1,2,3,5])
(a
b = np.array([[3,5,6,7], [8,9,10,11]])
(b)

array([[ 3,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
#6i
b.shape

(2, 4)

In [18]:
#6ii. You can also reshape it by using reshape(): # it returns the array with a modified shape

b.reshape(2, 4)

array([[ 3,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
#6iii. ravel() returns the array, flattened 
b.ravel()

array([ 3,  5,  6,  7,  8,  9, 10, 11])

In [20]:
#6iv. Transpose () returns the array, transposed 
b.T 

array([[ 3,  8],
       [ 5,  9],
       [ 6, 10],
       [ 7, 11]])

### Accessing or changing specific elements, rows, columns etc

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### 7. To get a specific element[row, column]


In [22]:
a[0,3]

4

In [23]:
a[1, 4]

12

In [24]:
# 7ii. To get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
#7 iii. To get specific column from the 2 dimension array
a[:, 5]

array([ 6, 13])

#### 8. To get start index, end index, step size

In [26]:
a[1, 1:6:2]

array([ 9, 11, 13])

#### 9. To change a value in the array set

In [30]:
a[1,5] = 25    # it will replace index 5 in the 2nd row with 25
print(a)

#To replace say 4,11 column with 15
a[:, 3] =15
a

[[ 1  2  3 15  5  6  7]
 [ 8  9 10 15 12 25 14]]


array([[ 1,  2,  3, 15,  5,  6,  7],
       [ 8,  9, 10, 15, 12, 25, 14]])

### 10. 3Dimension array 

In [31]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [32]:
#10i. To get a specific element(work outside in)
c[2,0,1]

14

In [33]:
#10ii. To get all the first row of each dimension
c[:,0,:]    

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [34]:
#10iii. To replace a specific values to the array

c[:,0,:] = [[9,9,9],[8,8,8],[7,7,7]]
c

array([[[ 9,  9,  9],
        [ 4,  5,  6]],

       [[ 8,  8,  8],
        [10, 11, 12]],

       [[ 7,  7,  7],
        [16, 17, 18]]])

### Aggregate Functions

#### 11. #Sum Functions: The arr.sum() function is  used to compute the sum of all elements, the sum of each row,and the sum of each column of a given array. 

In [35]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.sum())

45


#### 12. maximum number: the arr.max() function is used to return the maximun number in a given array.

In [36]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.max())

9


#### 13. Minimum number:  the arr.min() function is used to return the maximun number in a given array.

In [37]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.min())

1


#### 14. Mean:  the arr.mean() function is used to find the average in a given array.

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.mean())

#### 15. Median:  the np.median() function is used to find the median in a given array.

In [38]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.median(arr))

5.0


### Initializing different types of arrays


#### 16. All 0s matrix-  This displayes all 0s to both rows and column

In [40]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
#16i. All ones matix
np.ones((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 17. If you want to initialise a matric with a dfferent num
##### full function

In [42]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [43]:
#17i. Apply any number to the whole array: 
np.full_like(c,4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

### To initialize a matric array of random decimal numbers

#### 18. To get a random number

In [44]:
np.random.random()

0.7756773122094154

In [45]:
#18i. If you want to generate the same random number again and again
np.random.seed(100)
np.random.random()

0.5434049417909654

In [46]:
#18ii. To initialize a matric array of random decimal numbers
np.random.rand(3,3,2)

array([[[0.27836939, 0.42451759],
        [0.84477613, 0.00471886],
        [0.12156912, 0.67074908]],

       [[0.82585276, 0.13670659],
        [0.57509333, 0.89132195],
        [0.20920212, 0.18532822]],

       [[0.10837689, 0.21969749],
        [0.97862378, 0.81168315],
        [0.17194101, 0.81622475]]])

#### 19. repeat array- repeats numbers in array based on the specific value set to it.

In [47]:
d = np.array([1,2,3])
r1 = np.repeat(d,2)
print(r1)

[1 1 2 2 3 3]


In [49]:
 #19i. To repeat array with specified axis

d = np.array([[1,2,3]])
r1 = np.repeat(d,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### 20.  Standard Deviation:np.std() is used to compute the standard deviation along the specified axis. It returns the standard deviation of the array elements. 

In [51]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.std(arr))

2.581988897471611


## 20 Pandas Functions

### 1. Pandas read_() function. This is used to read a file 

In [1]:
import pandas as pd
df = pd.read_excel('Order_sales2.xlsx')

### 2. Pandas head() and df.tail() function is used to get the top and bottom of the data set

In [122]:
df.head()

Order Quantity       Sales  Discount       Ship Mode     Profit  \
0               6    261.5400      0.04     Regular Air  -213.2500   
1              49  10123.0200      0.07  Delivery Truck   457.8100   
2              27    244.5700      0.01     Regular Air    46.7075   
3              30   4965.7595      0.08     Regular Air  1198.9710   
4              19    394.2700      0.08     Regular Air    30.9400   

   Unit Price  Shipping Cost       Customer Name Province   Region  \
0       38.94          35.00  Muhammed MacIntyre  Nunavut  Nunavut   
1      208.16          68.02        Barry French  Nunavut  Nunavut   
2        8.69           2.99        Barry French  Nunavut  Nunavut   
3      195.99           3.99       Clay Rozendal  Nunavut  Nunavut   
4       21.78           5.94      Carlos Soltero  Nunavut  Nunavut   

  Customer Segment Product Category            Product Sub-Category  \
0   Small Business  Office Supplies          Storage & Organization   
1         Consumer  Office Supplies                      Appliances   
2         Consumer  Office Supplies  Binders and Binder Accessories   
3        Corporate       Technology    Telephones and Communication   
4         Consumer  Office Supplies                      Appliances   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum   
2   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl         Small Box   
3                                               R380         Small Box   
4                           Holmes HEPA Air Purifier        Medium Box   

   Product Base Margin  Ship Date  
0                 0.80 2010-10-20  
1                 0.58 2012-10-02  
2                 0.39 2012-10-03  
3                 0.58 2011-07-12  
4                 0.50 2010-08-30

In [23]:
df.tail()

Order Quantity      Sales  Discount       Ship Mode   Profit  \
8394               8  1294.0400      0.05  Delivery Truck -323.180   
8395              23   392.5700      0.04     Regular Air   22.250   
8396              37   823.7800      0.03     Express Air  343.050   
8397               8   469.8375      0.00     Regular Air -159.236   
8398              20  2026.0100      0.10     Express Air  580.430   

      Unit Price  Shipping Cost    Customer Name Province Region  \
8394      150.98          66.27       Mick Brown  Alberta   West   
8395       17.07           8.13       Mick Brown  Alberta   West   
8396       22.23           5.08     Frank Hawley  Alberta   West   
8397       65.99           8.99     Frank Hawley  Alberta   West   
8398      105.98          13.99  Grant Donatelli  Alberta   West   

     Customer Segment Product Category          Product Sub-Category  \
8394         Consumer        Furniture                     Bookcases   
8395         Consumer  Office Supplies                     Envelopes   
8396      Home Office        Furniture            Office Furnishings   
8397      Home Office       Technology  Telephones and Communication   
8398         Consumer        Furniture            Office Furnishings   

                                           Product Name Product Container  \
8394                        Bush Mission Pointe Library         Jumbo Box   
8395  Recycled Interoffice Envelopes with Re-Use-A-S...         Small Box   
8396                          Executive Impressions 14"        Small Pack   
8397                                    Talkabout T8367         Small Box   
8398  Tenex 46" x 60" Computer Anti-Static Chairmat,...        Medium Box   

      Product Base Margin  Ship Date  
8394                 0.65 2010-08-09  
8395                 0.38 2010-08-11  
8396                 0.41 2011-04-10  
8397                 0.56 2011-04-09  
8398                 0.65 2009-02-11

### 3. Pandas info() function. this function is used to get the complete information about all columns in the table

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Order Quantity        8399 non-null   int64         
 1   Sales                 8399 non-null   float64       
 2   Discount              8399 non-null   float64       
 3   Ship Mode             8399 non-null   object        
 4   Profit                8399 non-null   float64       
 5   Unit Price            8399 non-null   float64       
 6   Shipping Cost         8399 non-null   float64       
 7   Customer Name         8399 non-null   object        
 8   Province              8399 non-null   object        
 9   Region                8399 non-null   object        
 10  Customer Segment      8399 non-null   object        
 11  Product Category      8399 non-null   object        
 12  Product Sub-Category  8399 non-null   object        
 13  Product Name      

### 4. Pandas shape and size function is used to get the shape and size of a dataset

In [26]:
df.shape

(8399, 17)

In [27]:
df.size

142783

### 5. Pandas sample(n) functions, is used to choose n number of random sample from the dataset 

In [2]:
df.sample(n=5)

Order Quantity    Sales  Discount       Ship Mode  Profit  Unit Price  \
6871               4  1121.78      0.04  Delivery Truck -454.80      270.98   
479                4    14.23      0.00     Regular Air   -4.43        2.08   
4258              40   718.60      0.08     Regular Air  -81.49       17.98   
932               17  3816.59      0.01  Delivery Truck  191.47      208.16   
2508              21   736.17      0.01     Regular Air  232.99       35.41   

      Shipping Cost   Customer Name              Province    Region  \
6871          50.00  Thea Hendricks                 Yukon     Yukon   
479            5.33   Doug Bickford  Prince Edward Island  Atlantic   
4258           4.00   Karen Daniels               Ontario   Ontario   
932           68.02    Sonia Sunley      British Columbia      West   
2508           1.99     Jim Mitchum               Ontario   Ontario   

     Customer Segment Product Category  Product Sub-Category  \
6871      Home Office        Furniture    Chairs & Chairmats   
479         Corporate        Furniture    Office Furnishings   
4258         Consumer       Technology  Computer Peripherals   
932         Corporate  Office Supplies            Appliances   
2508         Consumer       Technology  Computer Peripherals   

                                           Product Name Product Container  \
6871  Global Enterprise Series Seating High-Back Swi...        Jumbo Drum   
479                        Eldon® Wave Desk Accessories         Small Box   
4258  Belkin 107-key enhanced keyboard, USB/PS/2 int...         Small Box   
932   1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum   
2508                              Imation DVD-RAM discs        Small Pack   

      Product Base Margin  Ship Date  
6871                 0.77 2012-07-22  
479                  0.43 2012-07-11  
4258                 0.79 2011-11-16  
932                  0.58 2012-06-27  
2508                 0.43 2010-05-13

### 6. Pandas describe() function is used to get the mathematical analysis of each column of the dataset

In [30]:
df.describe()

Order Quantity         Sales     Discount        Profit   Unit Price  \
count     8399.000000   8399.000000  8399.000000   8399.000000  8399.000000   
mean        25.571735   1775.878179     0.049671    181.184422    89.346259   
std         14.481071   3585.050525     0.031823   1196.653326   290.354383   
min          1.000000      2.240000     0.000000 -14140.701600     0.990000   
25%         13.000000    143.195000     0.020000    -83.315000     6.480000   
50%         26.000000    449.420000     0.050000     -1.500000    20.990000   
75%         38.000000   1709.320000     0.080000    162.748000    85.990000   
max         50.000000  89061.050000     0.250000  27220.690000  6783.020000   

       Shipping Cost  Product Base Margin  
count    8399.000000          8336.000000  
mean       12.838557             0.512513  
std        17.264052             0.135589  
min         0.490000             0.350000  
25%         3.300000             0.380000  
50%         6.070000             0.520000  
75%        13.990000             0.590000  
max       164.730000             0.850000

In [32]:
df.describe().T

count         mean          std         min      25%  \
Order Quantity       8399.0    25.571735    14.481071      1.0000   13.000   
Sales                8399.0  1775.878179  3585.050525      2.2400  143.195   
Discount             8399.0     0.049671     0.031823      0.0000    0.020   
Profit               8399.0   181.184422  1196.653326 -14140.7016  -83.315   
Unit Price           8399.0    89.346259   290.354383      0.9900    6.480   
Shipping Cost        8399.0    12.838557    17.264052      0.4900    3.300   
Product Base Margin  8336.0     0.512513     0.135589      0.3500    0.380   

                        50%       75%       max  
Order Quantity        26.00    38.000     50.00  
Sales                449.42  1709.320  89061.05  
Discount               0.05     0.080      0.25  
Profit                -1.50   162.748  27220.69  
Unit Price            20.99    85.990   6783.02  
Shipping Cost          6.07    13.990    164.73  
Product Base Margin    0.52     0.590      0.85

### 7. Pandas nunique() function is an important function in pandas which is used to find the distinct values and it also tell us how many categorical variables are there in your dataset 

In [36]:
df.nunique()

Order Quantity            50
Sales                   8153
Discount                  16
Ship Mode                  3
Profit                  7986
Unit Price               751
Shipping Cost            652
Customer Name            795
Province                  13
Region                     8
Customer Segment           4
Product Category           3
Product Sub-Category      17
Product Name            1263
Product Container          7
Product Base Margin       51
Ship Date               1450
dtype: int64

### 8. Pandas.isna().any() function, is used to find if there is any varible or column with missing value

In [38]:
df.isna().any()

Order Quantity          False
Sales                   False
Discount                False
Ship Mode               False
Profit                  False
Unit Price              False
Shipping Cost           False
Customer Name           False
Province                False
Region                  False
Customer Segment        False
Product Category        False
Product Sub-Category    False
Product Name            False
Product Container       False
Product Base Margin      True
Ship Date               False
dtype: bool

### 9. Pandas isnull() Function - This function shows the row and column with boolean for the data present in the cell. True means null value , False means not a null value

In [39]:
df.isnull()

Order Quantity  Sales  Discount  Ship Mode  Profit  Unit Price  \
0              False  False     False      False   False       False   
1              False  False     False      False   False       False   
2              False  False     False      False   False       False   
3              False  False     False      False   False       False   
4              False  False     False      False   False       False   
...              ...    ...       ...        ...     ...         ...   
8394           False  False     False      False   False       False   
8395           False  False     False      False   False       False   
8396           False  False     False      False   False       False   
8397           False  False     False      False   False       False   
8398           False  False     False      False   False       False   

      Shipping Cost  Customer Name  Province  Region  Customer Segment  \
0             False          False     False   False             False   
1             False          False     False   False             False   
2             False          False     False   False             False   
3             False          False     False   False             False   
4             False          False     False   False             False   
...             ...            ...       ...     ...               ...   
8394          False          False     False   False             False   
8395          False          False     False   False             False   
8396          False          False     False   False             False   
8397          False          False     False   False             False   
8398          False          False     False   False             False   

      Product Category  Product Sub-Category  Product Name  Product Container  \
0                False                 False         False              False   
1                False                 False         False              False   
2                False                 False         False              False   
3                False                 False         False              False   
4                False                 False         False              False   
...                ...                   ...           ...                ...   
8394             False                 False         False              False   
8395             False                 False         False              False   
8396             False                 False         False              False   
8397             False                 False         False              False   
8398             False                 False         False              False   

      Product Base Margin  Ship Date  
0                   False      False  
1                   False      False  
2                   False      False  
3                   False      False  
4                   False      False  
...                   ...        ...  
8394                False      False  
8395                False      False  
8396                False      False  
8397                False      False  
8398                False      False  

[8399 rows x 17 columns]

### 10. Pandas isnull().sum() this function finds the number of null values in each colunm. this function tells you if to ignore a column or not

In [52]:
df.isnull().sum()

Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

### 11. df.columns, this function get the names of the column

In [54]:
df.columns 

Index(['Order Quantity', 'Sales', 'Discount', 'Ship Mode', 'Profit',
       'Unit Price', 'Shipping Cost', 'Customer Name', 'Province', 'Region',
       'Customer Segment', 'Product Category', 'Product Sub-Category',
       'Product Name', 'Product Container', 'Product Base Margin',
       'Ship Date'],
      dtype='object')

### 12. Pandas nlargest() function  is used to get n largest values from a data frame or a series. It Return the first n rows with the largest values in columns, in descending order. The columns that are not specified are returned as well, but not used for ordering

In [119]:
df.nlargest(10,"Profit")

Order Quantity     Sales  Discount       Ship Mode      Profit  \
4674              13  89061.05      0.00     Regular Air  27220.6900   
5609              49  28359.40      0.05     Regular Air  14440.3900   
4767              50  28664.52      0.09     Regular Air  13340.2600   
6995              49  29884.60      0.05     Regular Air  12748.8600   
7906              35  26095.13      0.03  Delivery Truck  12606.8100   
8268              46  27720.98      0.07     Regular Air  11984.3950   
3648              48  27820.34      0.08     Regular Air  11630.1460   
5646              38  29186.49      0.05  Delivery Truck  11562.0800   
3525              20  25409.63      0.02     Regular Air  11535.2820   
175               18  23792.93      0.00     Regular Air  10951.3065   

      Unit Price  Shipping Cost      Customer Name               Province  \
4674     6783.02          24.49         Emily Phan          New Brunswick   
5609      574.74          24.49        Andy Reiter            Saskachewan   
4767      599.99          24.49  Deborah Brumfield               Manitoba   
6995      599.99          24.49     Karen Carlisle       British Columbia   
7906      808.49          55.30        Rick Wilson                Alberta   
8268      599.99          24.49       Raymond Book                Alberta   
3648      599.99          24.49   Logan Haushalter                 Quebec   
5646      808.49          55.30      Nick Crebassa            Saskachewan   
3525     1270.99          19.99     John Stevenson                 Quebec   
175      1270.99          19.99      Grant Carroll  Northwest Territories   

                     Region Customer Segment Product Category  \
4674               Atlantic         Consumer       Technology   
5609                 Prarie        Corporate       Technology   
4767                 Prarie   Small Business       Technology   
6995                   West        Corporate       Technology   
7906                   West         Consumer       Technology   
8268                   West         Consumer       Technology   
3648                 Quebec        Corporate       Technology   
5646                 Prarie        Corporate       Technology   
3525                 Quebec   Small Business  Office Supplies   
175   Northwest Territories   Small Business  Office Supplies   

                Product Sub-Category  \
4674                 Office Machines   
5609                 Office Machines   
4767                 Copiers and Fax   
6995                 Copiers and Fax   
7906                 Office Machines   
8268                 Copiers and Fax   
3648                 Copiers and Fax   
5646                 Office Machines   
3525  Binders and Binder Accessories   
175   Binders and Binder Accessories   

                                           Product Name Product Container  \
4674   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
5609  Polycom ViaVideo™ Desktop Video Communications...         Large Box   
4767               Hewlett Packard LaserJet 3310 Copier         Large Box   
6995                      Canon Image Class D660 Copier         Large Box   
7906  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
8268               Hewlett Packard LaserJet 3310 Copier         Large Box   
3648               Hewlett Packard LaserJet 3310 Copier         Large Box   
5646  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
3525  Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box   
175   Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box   

      Product Base Margin  Ship Date  
4674                 0.39 2009-03-22  
5609                 0.37 2009-01-10  
4767                 0.37 2011-03-15  
6995                 0.44 2010-01-13  
7906                 0.40 2009-08-07  
8268                 0.37 2011-07-04  
3648                 0.37 2010-01-08  
5646                 0.40 2011-07-08  
3525     

In [62]:
df.nlargest(10,"Sales")

Order Quantity     Sales  Discount       Ship Mode     Profit  \
4674              13  89061.05      0.00     Regular Air  27220.690   
3512               7  45923.76      0.07     Regular Air    102.610   
5861               8  41343.21      0.09     Regular Air   3852.190   
3572               9  33367.85      0.01     Regular Air   3992.520   
6995              49  29884.60      0.05     Regular Air  12748.860   
4806              34  29345.27      0.03  Delivery Truck   7497.550   
5646              38  29186.49      0.05  Delivery Truck  11562.080   
1510               8  28761.52      0.04     Regular Air    285.113   
4767              50  28664.52      0.09     Regular Air  13340.260   
7903              33  28389.14      0.07  Delivery Truck   7132.180   

      Unit Price  Shipping Cost      Customer Name          Province  \
4674     6783.02          24.49         Emily Phan     New Brunswick   
3512     6783.02          24.49    Jasper Cacioppo            Quebec   
5861     6783.02          24.49     Craig Carreira       Saskachewan   
3572     3499.99          24.49        Dennis Kane            Quebec   
6995      599.99          24.49     Karen Carlisle  British Columbia   
4806      880.98          44.55      Steve Chapman          Manitoba   
5646      808.49          55.30      Nick Crebassa       Saskachewan   
1510     3499.99          24.49     Parhena Norris          Manitoba   
4767      599.99          24.49  Deborah Brumfield          Manitoba   
7903      880.98          44.55   Valerie Takahito           Alberta   

        Region Customer Segment Product Category Product Sub-Category  \
4674  Atlantic         Consumer       Technology      Office Machines   
3512    Quebec      Home Office       Technology      Office Machines   
5861    Prarie        Corporate       Technology      Office Machines   
3572    Quebec   Small Business       Technology      Copiers and Fax   
6995      West        Corporate       Technology      Copiers and Fax   
4806    Prarie        Corporate        Furniture            Bookcases   
5646    Prarie        Corporate       Technology      Office Machines   
1510    Prarie      Home Office       Technology      Copiers and Fax   
4767    Prarie   Small Business       Technology      Copiers and Fax   
7903      West         Consumer        Furniture            Bookcases   

                                           Product Name Product Container  \
4674   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
3512   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
5861   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
3572              Canon imageCLASS 2200 Advanced Copier         Large Box   
6995                      Canon Image Class D660 Copier         Large Box   
4806  Riverside Palais Royal Lawyers Bookcase, Royal...         Jumbo Box   
5646  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
1510              Canon imageCLASS 2200 Advanced Copier         Large Box   
4767               Hewlett Packard LaserJet 3310 Copier         Large Box   
7903  Riverside Palais Royal Lawyers Bookcase, Royal...         Jumbo Box   

      Product Base Margin  Ship Date  
4674                 0.39 2009-03-22  
3512                 0.39 2009-01-08  
5861                 0.39 2012-05-23  
3572                 0.37 2012-12-04  
6995                 0.44 2010-01-13  
4806                 0.62 2011-11-24  
5646                 0.40 2011-07-08  
1510                 0.37 2010-10-23  
4767                 0.37 2011-03-15  
7903                 0.62 2010-01-05

In [64]:
df.nsmallest(10,"Profit")

Order Quantity     Sales  Discount       Ship Mode      Profit  \
8313               3  18888.00      0.09     Regular Air -14140.7016   
7677               3  19707.20      0.04     Regular Air -12557.9976   
7968               3  21366.51      0.00     Regular Air -11984.3979   
5913               1   3457.99      0.05     Regular Air -11861.4600   
4661               1   3550.28      0.06     Express Air -11769.1700   
200               30  26133.39      0.04  Delivery Truck -11053.6000   
7571               4  19014.24      0.06     Regular Air -10263.6597   
3493              28  24391.16      0.04  Delivery Truck  -9611.9100   
6920               4  13698.96      0.05     Regular Air  -9078.9400   
6946               3   9172.32      0.06  Delivery Truck  -8570.4483   

      Unit Price  Shipping Cost     Customer Name               Province  \
8313     6783.02          24.49          Roy Phan                Alberta   
7677     6783.02          24.49    Laurel Workman                Alberta   
7968     6783.02          24.49     Adrian Barton                Alberta   
5913     3499.99          24.49  Maxwell Schwartz            Saskachewan   
4661     3499.99          24.49      Nathan Mautz          New Brunswick   
200       880.98          44.55        Julia West  Northwest Territories   
7571     6783.02          24.49       Roger Demir                Alberta   
3493      880.98          44.55     Julia Barnett                 Quebec   
6920     3499.99          24.49       Cyra Reiten                  Yukon   
6946     3502.14           8.73      Irene Maddox                  Yukon   

                     Region Customer Segment Product Category  \
8313                   West         Consumer       Technology   
7677                   West      Home Office       Technology   
7968                   West   Small Business       Technology   
5913                 Prarie        Corporate       Technology   
4661               Atlantic        Corporate       Technology   
200   Northwest Territories      Home Office        Furniture   
7571                   West         Consumer       Technology   
3493                 Quebec        Corporate        Furniture   
6920                  Yukon         Consumer       Technology   
6946                  Yukon         Consumer       Technology   

     Product Sub-Category                                       Product Name  \
8313      Office Machines   Polycom ViewStation™ ISDN Videoconferencing Unit   
7677      Office Machines   Polycom ViewStation™ ISDN Videoconferencing Unit   
7968      Office Machines   Polycom ViewStation™ ISDN Videoconferencing Unit   
5913      Copiers and Fax              Canon imageCLASS 2200 Advanced Copier   
4661      Copiers and Fax              Canon imageCLASS 2200 Advanced Copier   
200             Bookcases  Riverside Palais Royal Lawyers Bookcase, Royal...   
7571      Office Machines   Polycom ViewStation™ ISDN Videoconferencing Unit   
3493            Bookcases  Riverside Palais Royal Lawyers Bookcase, Royal...   
6920      Copiers and Fax              Canon imageCLASS 2200 Advanced Copier   
6946      Office Machines  Okidata Pacemark 4410N Wide Format Dot Matrix ...   

     Product Container  Product Base Margin  Ship Date  
8313         Large Box                 0.39 2009-03-14  
7677         Large Box                 0.39 2009-10-19  
7968         Large Box                 0.39 2011-11-28  
5913         Large Box                 0.37 2011-02-08  
4661         Large Box                 0.37 2009-03-04  
200          Jumbo Box                 0.62 2009-01-07  
7571         Large Box                 0.39 2010-09-14  
3493         Jumbo Box                 0.62 2012-12-13  
6920         Large Box                 0.37 2012-10-03  
6946         Jumbo Box                 0.57 2011-07-09

### 13. Pandas nsmallest() function is used to get n least values from a data frame or a series

In [65]:
df.nsmallest(10,"Sales")

Order Quantity  Sales  Discount    Ship Mode  Profit  Unit Price  \
1066               1   2.24      0.01  Regular Air -1.9700        1.48   
7661               1   3.20      0.09  Regular Air -3.1625        1.88   
6495               2   3.23      0.06  Regular Air -2.7300        1.26   
7224               1   3.41      0.06  Regular Air -1.7800        2.88   
3343               1   3.42      0.05  Regular Air -2.9095        1.88   
1672               1   3.63      0.03  Regular Air -1.5600        2.88   
2655               1   3.77      0.09  Regular Air -1.8400        2.94   
7247               1   3.85      0.08  Regular Air -1.3600        3.08   
3581               3   3.96      0.10  Regular Air -1.7200        1.14   
4361               3   4.94      0.10  Regular Air -1.7600        1.48   

      Shipping Cost       Customer Name          Province   Region  \
1066           0.70     Ricardo Emerson  British Columbia     West   
7661           1.49            Ken Dana           Alberta     West   
6495           0.70  Benjamin Patterson             Yukon    Yukon   
7224           0.70           Adam Hart  British Columbia     West   
3343           1.49         Andy Reiter            Quebec   Quebec   
1672           0.70     Maria Bertelson           Ontario  Ontario   
2655           0.96    Katrina Bavinger           Ontario  Ontario   
7247           0.99           Adam Hart  British Columbia     West   
3581           0.70        Jeremy Farry            Quebec   Quebec   
4361           0.70           Don Weiss           Ontario  Ontario   

     Customer Segment Product Category            Product Sub-Category  \
1066        Corporate  Office Supplies                    Rubber Bands   
7661   Small Business  Office Supplies  Binders and Binder Accessories   
6495        Corporate  Office Supplies                    Rubber Bands   
7224        Corporate  Office Supplies             Pens & Art Supplies   
3343        Corporate  Office Supplies  Binders and Binder Accessories   
1672        Corporate  Office Supplies             Pens & Art Supplies   
2655      Home Office  Office Supplies             Pens & Art Supplies   
7247        Corporate  Office Supplies                          Labels   
3581   Small Business  Office Supplies                    Rubber Bands   
4361        Corporate  Office Supplies                    Rubber Bands   

                             Product Name Product Container  \
1066                  Binder Clips by OIC          Wrap Bag   
7661  Staples® General Use 3-Ring Binders         Small Box   
6495                  Bagged Rubber Bands          Wrap Bag   
7224                           Newell 346          Wrap Bag   
3343  Staples® General Use 3-Ring Binders         Small Box   
1672                           Newell 335          Wrap Bag   
2655                           Newell 343          Wrap Bag   
7247                            Avery 481         Small Box   
3581                      OIC Thumb-Tacks          Wrap Bag   
4361                  Binder Clips by OIC          Wrap Bag   

      Product Base Margin  Ship Date  
1066                 0.37 2011-08-09  
7661                 0.37 2011-11-21  
6495                 0.81 2010-07-04  
7224                 0.56 2010-01-23  
3343                 0.37 2009-04-15  
1672                 0.56 2012-01-29  
2655                 0.58 2009-02-26  
7247                 0.37 2010-01-31  
3581                 0.38 2012-04-27  
4361                 0.37 2012-03-12

### 14. Pandas loc[] function The loc property is used to access a group of rows and columns by label(s) or a boolean array. .loc[] is primarily label based, but may also be used with a boolean array.

In [74]:
df.loc[1:6, ["Region","Sales","Profit","Order Quantity", "Customer Segment","Product Category"]]

Region       Sales     Profit  Order Quantity Customer Segment  \
1  Nunavut  10123.0200   457.8100              49         Consumer   
2  Nunavut    244.5700    46.7075              27         Consumer   
3  Nunavut   4965.7595  1198.9710              30        Corporate   
4  Nunavut    394.2700    30.9400              19         Consumer   
5  Nunavut    146.6900     4.4300              21         Consumer   
6  Nunavut     93.5400   -54.0385              12        Corporate   

  Product Category  
1  Office Supplies  
2  Office Supplies  
3       Technology  
4  Office Supplies  
5        Furniture  
6  Office Supplies

### 15. The Pandas iloc[] provides a unique function to retrieve rows from a Data Frame. Dataframe. The iloc property gets, or sets, the value(s) of the specified indexes

In [141]:
df.iloc[1:8,[0,1,2,3,4,5,6,7,8,12,14]]

Order Quantity       Sales  Discount       Ship Mode     Profit  \
1              49  10123.0200      0.07  Delivery Truck   457.8100   
2              27    244.5700      0.01     Regular Air    46.7075   
3              30   4965.7595      0.08     Regular Air  1198.9710   
4              19    394.2700      0.08     Regular Air    30.9400   
5              21    146.6900      0.05     Regular Air     4.4300   
6              12     93.5400      0.03     Regular Air   -54.0385   
7              22    905.0800      0.09     Regular Air   127.7000   

   Unit Price  Shipping Cost   Customer Name Province  \
1      208.16          68.02    Barry French  Nunavut   
2        8.69           2.99    Barry French  Nunavut   
3      195.99           3.99   Clay Rozendal  Nunavut   
4       21.78           5.94  Carlos Soltero  Nunavut   
5        6.64           4.95  Carlos Soltero  Nunavut   
6        7.30           7.72    Carl Jackson  Nunavut   
7       42.76           6.22    Carl Jackson  Nunavut   

             Product Sub-Category Product Container  
1                      Appliances        Jumbo Drum  
2  Binders and Binder Accessories         Small Box  
3    Telephones and Communication         Small Box  
4                      Appliances        Medium Box  
5              Office Furnishings        Small Pack  
6  Binders and Binder Accessories         Small Box  
7          Storage & Organization         Small Box

In [82]:
df[1:6]

Order Quantity       Sales  Discount       Ship Mode     Profit  \
1              49  10123.0200      0.07  Delivery Truck   457.8100   
2              27    244.5700      0.01     Regular Air    46.7075   
3              30   4965.7595      0.08     Regular Air  1198.9710   
4              19    394.2700      0.08     Regular Air    30.9400   
5              21    146.6900      0.05     Regular Air     4.4300   

   Unit Price  Shipping Cost   Customer Name Province   Region  \
1      208.16          68.02    Barry French  Nunavut  Nunavut   
2        8.69           2.99    Barry French  Nunavut  Nunavut   
3      195.99           3.99   Clay Rozendal  Nunavut  Nunavut   
4       21.78           5.94  Carlos Soltero  Nunavut  Nunavut   
5        6.64           4.95  Carlos Soltero  Nunavut  Nunavut   

  Customer Segment Product Category            Product Sub-Category  \
1         Consumer  Office Supplies                      Appliances   
2         Consumer  Office Supplies  Binders and Binder Accessories   
3        Corporate       Technology    Telephones and Communication   
4         Consumer  Office Supplies                      Appliances   
5         Consumer        Furniture              Office Furnishings   

                                        Product Name Product Container  \
1  1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum   
2   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl         Small Box   
3                                               R380         Small Box   
4                           Holmes HEPA Air Purifier        Medium Box   
5  G.E. Longer-Life Indoor Recessed Floodlight Bulbs        Small Pack   

   Product Base Margin  Ship Date  
1                 0.58 2012-10-02  
2                 0.39 2012-10-03  
3                 0.58 2011-07-12  
4                 0.50 2010-08-30  
5                 0.37 2010-08-30

### 16. Pandas groupby() functions allows you to split your data into separate groups to perform computation for better analysis 

In [90]:
df[['Sales','Profit']].groupby(df['Product Category']).mean()

Sales      Profit
Product Category                         
Furniture         3003.822820   68.116581
Office Supplies    814.048178  112.369080
Technology        2897.941008  429.207513

In [92]:
df[['Sales','Profit']].groupby(df['Product Category']).median()

Sales  Profit
Product Category                 
Furniture         1379.35 -14.250
Office Supplies    209.57  -3.845
Technology        1272.83  66.220

In [94]:
df[['Sales','Profit']].groupby(df['Region']).mean()

Sales      Profit
Region                                        
Atlantic               1865.044633  221.259827
Northwest Territories  2032.607435  255.464599
Nunavut                1473.120044   35.963506
Ontario                1677.553384  189.960888
Prarie                 1663.132826  188.253330
Quebec                 1933.668476  179.803578
West                   1806.905713  149.175578
Yukon                  1800.493304  136.253220

In [110]:
df[['Sales','Profit']].groupby(df['Product Category']).sum()

Sales         Profit
Product Category                            
Furniture         5178590.542  117432.986281
Office Supplies   3752762.100  518021.458000
Technology        5984248.182  886313.515300

### 17. Pandas sort_values() function is used to sort by the values along either axis.

In [142]:
df.sort_values(by = 'Profit', ascending = False )

Order Quantity     Sales  Discount       Ship Mode      Profit  \
4674              13  89061.05      0.00     Regular Air  27220.6900   
5609              49  28359.40      0.05     Regular Air  14440.3900   
4767              50  28664.52      0.09     Regular Air  13340.2600   
6995              49  29884.60      0.05     Regular Air  12748.8600   
7906              35  26095.13      0.03  Delivery Truck  12606.8100   
...              ...       ...       ...             ...         ...   
4661               1   3550.28      0.06     Express Air -11769.1700   
5913               1   3457.99      0.05     Regular Air -11861.4600   
7968               3  21366.51      0.00     Regular Air -11984.3979   
7677               3  19707.20      0.04     Regular Air -12557.9976   
8313               3  18888.00      0.09     Regular Air -14140.7016   

      Unit Price  Shipping Cost      Customer Name          Province  \
4674     6783.02          24.49         Emily Phan     New Brunswick   
5609      574.74          24.49        Andy Reiter       Saskachewan   
4767      599.99          24.49  Deborah Brumfield          Manitoba   
6995      599.99          24.49     Karen Carlisle  British Columbia   
7906      808.49          55.30        Rick Wilson           Alberta   
...          ...            ...                ...               ...   
4661     3499.99          24.49       Nathan Mautz     New Brunswick   
5913     3499.99          24.49   Maxwell Schwartz       Saskachewan   
7968     6783.02          24.49      Adrian Barton           Alberta   
7677     6783.02          24.49     Laurel Workman           Alberta   
8313     6783.02          24.49           Roy Phan           Alberta   

        Region Customer Segment Product Category Product Sub-Category  \
4674  Atlantic         Consumer       Technology      Office Machines   
5609    Prarie        Corporate       Technology      Office Machines   
4767    Prarie   Small Business       Technology      Copiers and Fax   
6995      West        Corporate       Technology      Copiers and Fax   
7906      West         Consumer       Technology      Office Machines   
...        ...              ...              ...                  ...   
4661  Atlantic        Corporate       Technology      Copiers and Fax   
5913    Prarie        Corporate       Technology      Copiers and Fax   
7968      West   Small Business       Technology      Office Machines   
7677      West      Home Office       Technology      Office Machines   
8313      West         Consumer       Technology      Office Machines   

                                           Product Name Product Container  \
4674   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
5609  Polycom ViaVideo™ Desktop Video Communications...         Large Box   
4767               Hewlett Packard LaserJet 3310 Copier         Large Box   
6995                      Canon Image Class D660 Copier         Large Box   
7906  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
...                                                 ...               ...   
4661              Canon imageCLASS 2200 Advanced Copier         Large Box   
5913              Canon imageCLASS 2200 Advanced Copier         Large Box   
7968   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
7677   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
8313   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   

      Product Base Margin  Ship Date  
4674                 0.39 2009-03-22  
5609                 0.37 2009-01-10  
4767                 0.37 2011-03-15  
6995                 0.44 2010-01-13  
7906                 0.40 2009-08-07  
...                   ...        ...  
4661                 0.37 2009-03-04  
5913                 0.37 2011-02-08  
7968                 0.39 2011-11-28  
7677                 0.39 2009-10-19  
8313                 0.39 2009-03-14  

[8399

### 18. Pandas query() function is used to query the columns of a DataFrame with a boolean expression.

In [114]:
df.query('Profit > 10000') [:20]

Order Quantity     Sales  Discount       Ship Mode      Profit  \
175               18  23792.93      0.00     Regular Air  10951.3065   
3525              20  25409.63      0.02     Regular Air  11535.2820   
3648              48  27820.34      0.08     Regular Air  11630.1460   
4643              43  21921.28      0.04  Delivery Truck  10521.3300   
4674              13  89061.05      0.00     Regular Air  27220.6900   
4767              50  28664.52      0.09     Regular Air  13340.2600   
5609              49  28359.40      0.05     Regular Air  14440.3900   
5646              38  29186.49      0.05  Delivery Truck  11562.0800   
6995              49  29884.60      0.05     Regular Air  12748.8600   
7906              35  26095.13      0.03  Delivery Truck  12606.8100   
8268              46  27720.98      0.07     Regular Air  11984.3950   

      Unit Price  Shipping Cost      Customer Name               Province  \
175      1270.99          19.99      Grant Carroll  Northwest Territories   
3525     1270.99          19.99     John Stevenson                 Quebec   
3648      599.99          24.49   Logan Haushalter                 Quebec   
4643      500.98          28.14       Nathan Mautz          New Brunswick   
4674     6783.02          24.49         Emily Phan          New Brunswick   
4767      599.99          24.49  Deborah Brumfield               Manitoba   
5609      574.74          24.49        Andy Reiter            Saskachewan   
5646      808.49          55.30      Nick Crebassa            Saskachewan   
6995      599.99          24.49     Karen Carlisle       British Columbia   
7906      808.49          55.30        Rick Wilson                Alberta   
8268      599.99          24.49       Raymond Book                Alberta   

                     Region Customer Segment Product Category  \
175   Northwest Territories   Small Business  Office Supplies   
3525                 Quebec   Small Business  Office Supplies   
3648                 Quebec        Corporate       Technology   
4643               Atlantic      Home Office       Technology   
4674               Atlantic         Consumer       Technology   
4767                 Prarie   Small Business       Technology   
5609                 Prarie        Corporate       Technology   
5646                 Prarie        Corporate       Technology   
6995                   West        Corporate       Technology   
7906                   West         Consumer       Technology   
8268                   West         Consumer       Technology   

                Product Sub-Category  \
175   Binders and Binder Accessories   
3525  Binders and Binder Accessories   
3648                 Copiers and Fax   
4643                 Office Machines   
4674                 Office Machines   
4767                 Copiers and Fax   
5609                 Office Machines   
5646                 Office Machines   
6995                 Copiers and Fax   
7906                 Office Machines   
8268                 Copiers and Fax   

                                           Product Name Product Container  \
175   Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box   
3525  Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box   
3648               Hewlett Packard LaserJet 3310 Copier         Large Box   
4643  Hewlett-Packard cp1700 [D, PS] Series Color In...        Jumbo Drum   
4674   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box   
4767               Hewlett Packard LaserJet 3310 Copier         Large Box   
5609  Polycom ViaVideo™ Desktop Video Communications...         Large Box   
5646  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
6995                      Canon Image Class D660 Copier         Large Box   
7906  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum   
8268               Hewlett Packard LaserJet 3310 Copier         Large Box   

      Product Base Margin  Sh

### 19 Pandas unique() function produces a Numpy array with the unique values.

In [145]:
df['Product Category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

### 20. Pandas memory_usage function is used to get the memory usage of each column in bytes

In [117]:
df.memory_usage()

Index                     128
Order Quantity          67192
Sales                   67192
Discount                67192
Ship Mode               67192
Profit                  67192
Unit Price              67192
Shipping Cost           67192
Customer Name           67192
Province                67192
Region                  67192
Customer Segment        67192
Product Category        67192
Product Sub-Category    67192
Product Name            67192
Product Container       67192
Product Base Margin     67192
Ship Date               67192
dtype: int64